### ISSUE TITLE
dws-jobtap: RPC futures could be leaked if plugin unloaded before responses

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-coral2#101]
The futures resulting from RPCs in the dws-jobtap plugin are only destroyed in their respective callbacks and therefore may be leaked if the plugin is unloaded or the broker stops before any responses. This can cause a hang at exit as seen in flux-framework/flux-core#5484.

One solution would be to tie destruction of these futures to the job with `flux_jobtap_job_aux_set()`. Another solution would be to collect outstanding futures in a list and destroy them all on plugin exit.

**Comment by jameshcorbett** [comment]
I think I prefer the aux idea, so I'll go with that and open a PR. Thanks!
