### ISSUE TITLE
Distributing rabbit hostnames as environment variables

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-coral2#104]
Marty McFadden asked whether Flux could export the hostname of the rabbit local to each compute node in a job. He wants to use the functionality described [here](https://nearnodeflash.github.io/v0.0.6/guides/user-containers/readme/#container-spec).

> I would like for the SCR library on each compute node to be able to open a socket to the available port on its local rabbit node.

The Flux-DWS plugins already export some DWS-specified environment variables. The variables are posted in an [eventlog entry](https://github.com/flux-framework/flux-coral2/blob/71818bfb7516aa22b7062fec28c007cd8c072ff4/src/job-manager/plugins/dws-jobtap.c#L639). I was thinking I could add a mapping from rabbit hostname to compute node hostlist to the event context, and let the job shell plugin set the right environment variable?

**Comment by grondo** [comment]
In case you were asking for feedback, I can't think of a much better way to do this than you've outline above.

My only idea is you could map the rabbit hostnames to job shell ranks (i.e. node ranks relative to the job) and just send set a single hostlist in the eventlog entry. This would make it easier for the job shell plugin, it could just render the hostname from the hostlist based on its rank in `flux_shell_info(3)` (the job shell rank).

**Comment by jameshcorbett** [comment]
I was asking for feedback actually, but even if I wasn't it's always helpful, so thanks! I think it will be easier in other places to send a mapping of hostlists though, since `cora2_dws.py` (which has the mapping from rabbits to compute nodes) won't always have the job shell ranks available.
