### ISSUE TITLE
Missing dependency on libsodium

### ISSUE THREAD

**Issue by mattaezell** [flux-framework/flux-coral2#108]
cray_pals_port_distributor.c uses functions from libsodium (specifically `randombytes_buf`) but the Makefile does not pull in the sodium library. This leads to undefined symbols at runtime. Maybe this previously came from flux-core's dependency on libsodium; I'm not sure, I haven't tracked it down.

**Comment by jameshcorbett** [comment]
Hmm @garlick is there something else I should use instead of libsodium or should I add it to the requirements?

**Comment by garlick** [comment]
For reference here's the commit that added this:  f05e076b18d47bbae3c617faeea6c7b9aa717b7

Did we decide this is used for some kind of security in the PMI implementation?  I mean it's tempting to just resort to `srandom(3)` and `random(3)` to construct 64 bit random numbers out of two 32 bit ones, but randomness is such a fraught topic in crypto we might want to stick with libsodium and avoid becoming the weak link.

I'll find the autmake runes for configuring libsodium....

**Comment by garlick** [comment]
This is what we have in configure.ac in the flux-security project:
```
PKG_CHECK_MODULES([SODIUM], [libsodium >= 1.0.14], [], [])
```
then something like
```diff
--- a/src/job-manager/plugins/Makefile.am
+++ b/src/job-manager/plugins/Makefile.am
@@ -6,6 +6,9 @@ AM_CFLAGS = \
 AM_LDFLAGS = \
        $(CODE_COVERAGE_LIBS)
 
+AM_CPPFLAGS = \
+       $(SODIUM_CFLAGS)
+
 jobtapdir = \
     $(fluxlibdir)/job-manager/plugins/
 
@@ -34,4 +37,5 @@ cray_pals_port_distributor_la_LDFLAGS = \
 
 cray_pals_port_distributor_la_LIBADD= \
     $(FLUX_CORE_LIBS) \
+    $(SODIUM_LIBS) \
     $(FLUX_HOSTLIST_LIBS)
```
