### ISSUE TITLE
Fluxion obtaining rabbit status upon restart

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-coral2#118]
When this [PR](https://github.com/flux-framework/flux-coral2/pull/117) is merged, flux-DWS will have the ability to send RPCs to fluxion reporting that certain rabbits are up or down.

Whenever Flux restarts, flux-DWS will send Fluxion the state of every rabbit.

However, whenever Fluxion restarts, it will assume all the rabbits are up, which could cause problems. If Flux itself restarts at the same time, flux-DWS will restart as well, and will send Fluxion the state of every rabbit. However, as @garlick noted [here](https://github.com/flux-framework/flux-coral2/pull/117#issuecomment-1845419039)

> That leaves the case of manually reloading the scheduler on a live system. This could come in handy, for example if we need to reconfigure or update the scheduler without affecting running jobs. However it's less likely that than the above situations which are a regular certainty.
> 
> ...We did take pains to make it possible to reload the scheduler so it would be good to not give that capability up on El Cap.

I could add some functionality to Fluxion so that whenever it comes online, it asks flux-coral2-dws for the status of all the rabbits. If flux-coral2-dws is down when the request is made, that's fine, all rabbit jobs will be rejected and Fluxion will get the status of the rabbits as soon as flux-coral2-dws comes back. Or perhaps there are no rabbits and so flux-coral2-dws isn't even installed, in which case Fluxion would need to ignore the ENOSYS message coming back from its RPC.

Does this sound reasonable @milroy @garlick ? It would mean adding some rabbit-specific logic to Fluxion. Thankfully I think it would be relatively minimal.

**Comment by garlick** [comment]
> It would mean adding some rabbit-specific logic to Fluxion. Thankfully I think it would be relatively minimal.

That does not seem ideal.

More thought/discussion required?  I'm not sure how critical this is - probably not as critical as getting the main drain functionality  working!

**Comment by jameshcorbett** [comment]
What if we required admins to restart the `flux-coral2-dws` service whenever they want to reload fluxion on a live system? If we added that requirement I think we could ensure that Fluxion has an accurate view of the resource status.

**Comment by jameshcorbett** [comment]
Resolved by https://github.com/flux-framework/flux-coral2/pull/120
