### ISSUE TITLE
Failure to read eventlog in `dws_environment` shell plugin

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-coral2#192]
Marty McFadden found that the `dws_environment` shell plugin failed repeatedly in his tests with the following error:

```
flux-shell[0]: ERROR: dws_environment: No 'dws_environment' event posted
flux-shell[0]: ERROR: dws_environment: Error reading DW environment from eventlog
flux-shell[0]: ERROR: plugin 'dws_environment': shell.init failed
flux-shell[0]: FATAL: shell_init: Invalid argument
```

The problem is intermittent, about a quarter of Marty's 600 jobs hit it. So I'm guessing it is hitting [the timeout](https://github.com/flux-framework/flux-coral2/blob/3a388c1bcdaf25bcd06b43f86c4bb32c1c2cdd23/src/shell/plugins/dws_environment.c#L96) waiting to read another event. I wonder if given the size of elcap, a higher timeout is necessary? The event is definitely there, it's posted before the dws jobtap prolog is removed, and also the administrative prolog waits for the same event to be posted. So I don't believe there is any race condition.

@grondo , any thoughts?

**Comment by grondo** [comment]
Remind me of the sequence of events here, starting with after the job `alloc` event is posted (job enters RUN state)?

**Comment by jameshcorbett** [comment]
1. `dws-prolog` jobtap prolog starts and so does the administrative prolog
2. `dws-jobtap.c` posts the `dws_environment` event and finishes its prolog (see [here](https://github.com/flux-framework/flux-coral2/blob/3a388c1bcdaf25bcd06b43f86c4bb32c1c2cdd23/src/job-manager/plugins/dws-jobtap.c#L636))
3. Administrative prolog (which has a script that waits for the `dws_environment` event) finishes
4. Shell starts (I presume?)
5. Plugin fails to read the `dws_environment` eventlog entry

**Comment by grondo** [comment]
Hm, so it sounds like the `dws_environment` event should be in the eventlog _before_ the job shell is even launched?
I'm at a loss why it could be taking >2s to get to that eventlog entry.

I guess one idea is that the job-info service or KVS could be "busy" and thus delivery of the responses is delayed.

If it isn't expected that the `dws_environment` event would ever be missing, you could extend the timeout by quite a bit just to catch the rare case where the event never shows up.

We could also try to devise a reproducer and add some debug to try to pinpoint what is happening. It may not be what I assume.

**Comment by grondo** [comment]
Oh, also, what size were the failing jobs? (was there any correlation with large job size?)

**Comment by jameshcorbett** [comment]
All the jobs were single-node, but Marty was launching a bunch of them, like 600 back-to-back using `flux submit`. People have definitely run much larger jobs and not reported this same issue, but I don't know if anyone has run *as many* jobs at once.

**Comment by grondo** [comment]
Maybe tomorrow I can instrument the shell plugin (easy to load an alternate version) and see if I can reproduce.

**Comment by grondo** [comment]
I've reproduced the issue using the following steps:


I started with a  modified `dws_environment.c` plugin with more debugging and verbose error handling:
(also, I've disabled the actual setting of the environment so the `rabbits` key in the event context doesn't have to be correct)

```diff
diff --git a/src/shell/plugins/dws_environment.c b/src/shell/plugins/dws_environment.c
index b042254..812f773 100644
--- a/src/shell/plugins/dws_environment.c
+++ b/src/shell/plugins/dws_environment.c
@@ -12,6 +12,7 @@
 #include <stdint.h>
 #include <stdlib.h>
 #include <unistd.h>
+#include <time.h>
 
 #include <jansson.h>
 
@@ -83,6 +84,34 @@ static int set_environment (flux_shell_t *shell,
     return -1;
 }
 
+static struct timespec ts_diff (struct timespec start, struct timespec end)
+{
+    struct timespec temp;
+    if ((end.tv_nsec-start.tv_nsec)<0) {
+            temp.tv_sec = end.tv_sec-start.tv_sec-1;
+            temp.tv_nsec = 1000000000+end.tv_nsec-start.tv_nsec;
+    } else {
+            temp.tv_sec = end.tv_sec-start.tv_sec;
+            temp.tv_nsec = end.tv_nsec-start.tv_nsec;
+    }
+    return temp;
+}
+
+double monotime_since (struct timespec t0)
+{
+    struct timespec ts, d;
+    clock_gettime (CLOCK_MONOTONIC, &ts);
+
+    d = ts_diff (t0, ts);
+
+    return ((double) d.tv_sec * 1000 + (double) d.tv_nsec / 1000000);
+}
+
+void monotime (struct timespec *tp)
+{
+    clock_gettime (CLOCK_MONOTONIC, tp);
+}
+
 /*
  * Read an eventlog future, looking for the 'dws_environment' event
  */
@@ -92,9 +121,24 @@ static int read_future (flux_shell_t *shell, flux_future_t *fut)
     json_t *context = NULL;
     json_t *env, *rabbit_mapping;
     const char *name, *event = NULL;
+    struct timespec t0;
+    bool print_time = true;
 
-    while (flux_future_wait_for (fut, 2.0) == 0
-           && flux_job_event_watch_get (fut, &event) == 0) {
+    monotime (&t0);
+
+    while (true) {
+        if (flux_future_wait_for (fut, 2.0) < 0) {
+            shell_log_errno ("flux_future_wait_for");
+            return -1;
+        }
+        if (print_time) {
+            shell_log ("%.3fs to get first event", monotime_since (t0)/1000);
+            print_time = false;
+        }
+        if (flux_job_event_watch_get (fut, &event) < 0) {
+            shell_log_errno ("flux_job_event_watch_get");
+            return -1;
+        }
         if (!(o = eventlog_entry_decode (event))) {
             shell_log_errno ("Error decoding eventlog entry");
             return -1;
@@ -104,8 +148,13 @@ static int read_future (flux_shell_t *shell, flux_future_t *fut)
             json_decref (o);
             return -1;
         }
+        shell_log ("got event %s", name);
         if (!strcmp (name, "dws_environment")) {
-            if (json_unpack (context,
+            json_error_t error;
+            if (json_unpack_ex (
+                             context,
+                             &error,
+                             0,
                              "{s:o, s:o}",
                              "variables",
                              &env,
@@ -113,12 +162,11 @@ static int read_future (flux_shell_t *shell, flux_future_t *fut)
                              &rabbit_mapping)
                 < 0) {
                 shell_log_error (
-                    "No 'variables' or 'rabbits' context "
-                    "in dws_environment event");
+                             "invalid dws_environment event: %s", error.text);
                 json_decref (o);
                 return -1;
             }
-            if (set_environment (shell, env, rabbit_mapping) < 0) {
+            if (false && set_environment (shell, env, rabbit_mapping) < 0) {
                 json_decref (o);
                 return -1;
             }
```
Then I launched a test instance with the following configuration that emits a fake `dws_environment` event to the job eventlog in the `job-manager.prolog`:
```toml
[job-manager]
plugins = [{ load = "perilog.so" }]

[job-manager.prolog]
command = [
  "sh",
  "-c",
  """
flux post-job-event \
  $FLUX_JOB_ID dws_environment \
  variables='{"DW_WORKFLOW_NAME":"fluxjob-xxyyzz"}' \
  rabbits='{"foo":"bar"}'"""
]
```

I ran one broker per core to simulate a larger instance and to be able to get more job shells active at once:
```console
$ flux alloc -q compute -N2 --conf=test.toml -o per-resource.type=core
```

Then launched 1024 jobs:
```console
$ flux submit --cc=1-1024 --setattr=dw=foo -o userrc=test.lua --progress --watch hostname
```

With the 2.0s timeout about, ~150 of the 1024 jobs fail.

Increasing the timeout to 10s, all of the jobs succeed. The maximum logged time to get the first event in this test was:
```
flux-shell[0]: dws_environment: 3.291s to get first event
```
The timeout could probably be increased even further, just to handle the worst case scenario. Maybe 30-60s?
