### ISSUE TITLE
RPM for cray-libpals jobtap and shell plugins

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-coral2#20]
From a team meeting---

For a permanent way to deploy Flux with the necessary libpals plugins on Cray systems, it would be good to create an RPM for just the parts of this repo that are necessary to work with Cray MPI.

**Comment by grondo** [comment]
The first step here would be to request a flux-coral2 repo in the toss4 buildfarm via a Jira ticket.

Then it will just be a matter of creating a spec file to build the RPM which contains the libpals plugins. I'd be happy to help here.

**Comment by jameshcorbett** [comment]
RPM made it through the TOSS4 build farm.
