### ISSUE TITLE
Add preset `run/batch/submit/alloc` flags for simplifying rabbit submission

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-coral2#200]
The normal way to ask for rabbit storage for a job is to add the `--setattr=dw="#DW jobdw type=xfs capacity=100GiB name=myname"` option to `flux submit/run/batch/alloc` but I was discussing today with @behlendorf whether there could be some simpler preset flags with configurable meanings. What we discussed was something like have flags like `--small-xfs` or `--large-lustre` that simply add a `#DW` string to the user's job, where that string could be configured at the system level, maybe in a config file somewhere. This would just be to simplify things for most users, advanced users could still set the `dw` attribute directly.

Thoughts @garlick @grondo ?

**Comment by jameshcorbett** [comment]
> However, you could support these custom strings in jobspec attributes if that's acceptable, e.g. --setattr=dw=small-xfs or --setattr=dw=large-lustre.

That sounds reasonable to me. I'll check with Brian.

**Comment by jameshcorbett** [comment]
Presumably I could add a new config table that specifies what special shorthand strings are accepted and what their meaning is (i.e. what `#DW blah blah` they correspond to)? I'm 90% sure I know how to do that.

**Comment by grondo** [comment]
Yeah, good idea. That would allow admins to customize the list.

**Comment by jameshcorbett** [comment]
> If it helps, there's a proposal to add a -S short option for --setattr so users could use -S dw=small-xfs.

I do think this would be a big help.
