### ISSUE TITLE
Save a configurable number of `nnfdatamovement` resources to the KVS

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-coral2#212]
Saving every `nnfdatamovement` resource to jobs' KVS is probably not a good idea because the data for large jobs with XFS or GFS2 file systems could easily (?) get past 100KiB (see also #180 and particularly https://github.com/flux-framework/flux-coral2/issues/180#issuecomment-2229489974). However, it would be nice to have a way to store the data somewhat permanently in Flux, because currently it is deleted at the end of the job and is inaccessible to normal users anyway.

@bdevcich and @matthew-richerson and I discussed today saving a configurable number of `nnfdatamovement` resources to jobs' KVS. Hopefully saving just a few would be enough to do some meaningful debugging without burdening the KVS too much.

**Comment by jameshcorbett** [comment]
Any more detail on when we should save the resources? Before sending the workflow to `Teardown`? Only if the job hit an error or in all cases?

**Comment by bdevcich** [comment]
> Any more detail on when we should save the resources? Before sending the workflow to `Teardown`?

Yes, you'd want to save them before the transition to `Teardown` (but after `DataOut` is complete in the success case), otherwise you'd get incomplete data movement resources.

> Only if the job hit an error or in all cases?

I think in all cases since more data is better in my book, but I understand that conflicts with the KVS limitations.

**Comment by jameshcorbett** [comment]
It shall be done 🫡 . But in the error case, we should only save `nnfdatamovements` that hit an error? 

Thinking now that we won't be able to tell if a workflow hit an error because of data movement or something else entirely, so trying to find `nnfdatamovements` with an error set might not result in any matches. But I suppose we could just issue another GET call without the filter.

By the way, what is the filter we want to add to indentify data movements that had an issue?

**Comment by bdevcich** [comment]
You'd want to filter `nnfdatamovements` by the `state` and `status` fields:

This output includes a few failed data movements:

```
[blake@htx-lustre ~]$ kubectl get nnfdatamovements -A
NAMESPACE       NAME                             STATE      STATUS    ERROR   AGE
rabbit-node-1   fluxjob-301409051235844096-1-0   Finished   Success           3h45m
rabbit-node-1   fluxjob-301409051235844096-1-1   Finished   Success           3h45m
rabbit-node-2   fluxjob-301409051235844096-1-1   Finished   Success           3h45m
rabbit-node-2   fluxjob-301409051235844096-1-0   Finished   Success           3h45m
rabbit-node-2   nnf-dm-node-65l72                Finished   Failed    Fatal   3h44m
rabbit-node-2   nnf-dm-node-jfw4p                Finished   Failed    Fatal   3h44m
rabbit-node-1   nnf-dm-node-gggx2                Finished   Failed    Fatal   3h44m
rabbit-node-1   nnf-dm-node-6ddvl                Finished   Failed    Fatal   3h44m
```
