### ISSUE TITLE
libpals doesn't play well with attempting to oversubscribe cores

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-coral2#27]
A user was asking about running multiple MPI tasks per core on Tioga. It should be possible per  https://flux-framework.readthedocs.io/en/latest/faqs.html#how-can-i-oversubscribe-tasks-to-resources-in-flux. It works on corona:
```
[day36@corona178:~]$ flux resource list
     STATE NNODES   NCORES    NGPUS NODELIST
      free      1       48        8 corona178
 allocated      0        0        0 
      down      0        0        0
[day36@corona178:mpi_hello]$ flux mini run -n 48 -o per-resource.type=core -o per-resource.count=2 ./hello_corona
Number of MPI tasks is: 96

[day36@corona178:mpi_hello]$
```
but on tioga:
```
[day36@tioga24:mpi_hello]$ flux mini run -n64 -o per-resource.type=core -o per-resource.count=2 ./hello_tioga 
0.044s: flux-shell[0]: ERROR: libpals: taskid 64 (on node 0) >= ntasks 64
0.044s: flux-shell[0]: ERROR: libpals: Error initializing pals_pe_t structs
0.044s: flux-shell[0]: ERROR: plugin 'libpals': shell.init failed
0.044s: flux-shell[0]: FATAL: shell_init
0.044s: job.exception type=exec severity=0 shell_init
flux-job: task(s) exited with exit code 1
[day36@tioga24:mpi_hello]$
```

**Comment by ryanday36** [comment]
@jameshcorbett: did this make it into a release or Buildfarm RPM? I'm still seeing the same error on Tioga, so I'm trying to figure out if it's still an issue or if Tioga just didn't get the update. It looks like Tioga has flux-coral2-0.1.0-1.t4.x86_64.

**Comment by jameshcorbett** [comment]
Not into a release yet. Since you're asking though I will try to get a release out this week! I am a bit unclear on how updates work---should I try to get releases for this repo out before the TOSS updates or should I just make releases whenever it makes sense?

**Comment by ryanday36** [comment]
Great! Thanks James. Ben Casses and the folks doing acceptance testing are looking to be able to overcommit nodes on Tioga. In general, getting releases out before TOSS updates is good. I think it's easier for them to do out of cycle updates on this repo though, as it's not in the main TOSS image.
