### ISSUE TITLE
cray_pals plugin should accept task distribution from flux shell

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-coral2#35]
Problem: flux-core needs to support "cyclic" task distribution as mentioned in flux-framework/flux-core#4706.  I just opened flux-framework/flux-core#4725  against the flux-core pmi shell plugin to have it accept the shell's task distribution instead of just grabbing per-shell task counts and assuming a "block" task distribution.   I _think_ the cray_pals shell plugin is patterned after flux-core's pmi plugin.  At least I do see it fetching the `ntasks` key using `flux_shell_rank_info_unpack()` to get the task count per shell, rather than the `taskids` key which contains the actual task ranks.

To prepare for supporting cyclic distribution, the cray_pals plugin should communicate the task distribution assigned by the shell to the cray mpi stack.

**Comment by jameshcorbett** [comment]
Resolved by #128
