### ISSUE TITLE
jobtap plugin not loaded: disabling operation

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-coral2#52]
I happened to notice on rzvernal that this message appears when launching slurm -> flux -> cray MPI program:
```
rzvernal14 /g/g0/garlick > srun -N2 -n2 --mpi=pmi2 flux start flux run -o mpi=none -o verbose=2 -N2 proj/mpi-hello/hello
[snip]
0.062s: flux-shell[1]: DEBUG: libpals: jobtap plugin not loaded: disabling operation
[snip]
```
It's certainly expected behavior that the jobtap plugin is only loaded in the system instance, while the shell plugin gets loaded in all instances (at least when flux is run from the system path).

What's happening here?   How does the `cray_pals.so` shell plugin function when it cannot reach the `cray_pals_port_distributor.so` jobtap plugin?

My MPI program seems to be working despite the jobtap plugin not being loaded.

Note that due to flux-framework/flux-core#5045 and recent environment changes on LC coral2 systems, Cray MPI programs will no longer find the flux PMI2 library before the Cray one.  I just want to make sure that everything is going to keep working!

**Comment by jameshcorbett** [comment]
This sounds like an oversight on my part.

When the jobtap plugin isn't loaded, the shell plugin will still set the `PALS_` environment variables and create the `apinfo` file, but it won't set `PMI_CONTROL_PORT`, which is necessary when multiple multi-node jobs are running concurrently on the same nodes. Aside from that it shouldn't be an issue, which I think explains why you haven't had trouble. Not sure why anyone hasn't seen this on Tioga yet...

I think the simplest solution is to load the jobtap plugin in all instances. Any thoughts on how to accomplish that?

**Comment by garlick** [comment]
Pondering - thanks for the explanation!

**Comment by garlick** [comment]
I think @grondo has the winnig solution - providing an rc1 fragment to load the port allocator plugin.  That will apply to all instances.

I wonder if `flux-coral2` should provide this fragment.   Then the sys admins wouldn't need to manage the config - they would simply install the package on the systems that need it and leave it off on other systems.

For that to work, the flux-coral2 package wuld need to be packaged with the typical system prefix rather than /opt.  Was there a reason for homing the package in /opt?

We could also have it provide a lua.d fragment for loading the shell plugin and take that off the sys admins shoulders as well.

**Comment by jameshcorbett** [comment]
That all sounds reasonable. I believe flux-coral2 could be moved out of `/opt`. I think it was even supposed to be at one point.

**Comment by jameshcorbett** [comment]
@garlick I'm only realizing now---the jobtap plugin takes arguments when it's loaded, although at the moment I think it's always loaded with the default arguments on LC systems. But if that needs to change, admins will need to modify the rc script, right?

**Comment by garlick** [comment]
This is for `port-min` and `port-max`?   For the system instance, I guess those could be specified in the TOML config, but that won't affect subinstances.   For sub-instances where we don't have a default configuration I think you're right, the rc would have to be edited.  Maybe for now we can just compile in good defaults?  Not sure how much tweaking the port range is likely to need.

**Comment by grondo** [comment]
Dumb question: are the ports distributed by the system instance supposed to be inherited by subinstances?

**Comment by garlick** [comment]
@jameshcorbett can answer definitively but my understanding is "no".

I keep having to remind myself how this could possibly work because it seems wrong to have multiple allocators in the hierarchy that each think they have exclusive access to the whole range of ports.  Since I just had to think about it again for 10 minutes, I better write down my thoughts:  

I _think_ it works as a first approximation for a top level system instance that is node exclusive and one level of subinstance that is not node exclusive (that runs Cray MPI jobs).  That would maintain the invariant that there is only one allocator running MPI jobs per node.

If the system instance were not node exclusive or if the next level instance (assumed to not be node exclusive) launched additional instance that would be starting MPI jobs, then...too many popes.

**Comment by grondo** [comment]
Thanks for the clarification!
